name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 82767eb75559e14f53f909bdc018305f
        file_path: resume.json
